# This is a basic workflow to help you get started with Actions

name: Periodic update

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'data/**'
  pull_request:
    branches: [ master ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '1 0 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.1
      id: go

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install jq and protoc
      run: |
        sudo apt-get install jq protobuf-compiler
        jq --version
        protoc --version

    # Runs a single command using the runners shell
    - name: Run make
      run: make

    # Runs a set of commands using the runners shell
    - name: Check git diff
      run: |
        ls -la data/*
        git status
        git diff

    # Git commit + push, see https://github.com/github-actions-x/commit
    - name: Publish changes to git
      if: github.ref == 'refs/heads/master'
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'OstaniZdrav data update 🤖'
        rebase: 'true' # pull abd rebase before commit
        files: data/
        name: Corona Warn scrape bot 🤖
        email: info@sledilnik.org
